steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/trading-asst', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/trading-asst']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'trading-asst'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/trading-asst'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'trading-asst-sa@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--set-secrets'
      - 'OPENAI_API_KEY=openai-api-key:latest'
      - '--min-instances'
      - '${_MIN_INSTANCES}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      - '--timeout'
      - '${_TIMEOUT}'
      - '--concurrency'
      - '${_CONCURRENCY}'

substitutions:
  _REGION: us-central1  # Default region
  _REPOSITORY: trading-asst  # Default repository name
  _MIN_INSTANCES: "0"  # Minimum number of instances
  _MAX_INSTANCES: "3"  # Maximum number of instances
  _MEMORY: "1Gi"  # Memory per instance
  _CPU: "1"  # CPU cores per instance (1 = 1000m)
  _TIMEOUT: "600"  # Request timeout in seconds
  _CONCURRENCY: "1000"  # Maximum concurrent requests per instance

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/trading-asst' 